export const listing = {
  address:   "40 Meadowbrook Rd",
  city:      "Toronto",
  province:  "ON",
  price:     2800,
  beds:      3,
  baths:     2,
  sqft:      800,
  available: "Available Now",
  type:      "Apartment - Multiplex",
  contact: { email: "your@email.com", phone: "+1 (416) 000-0000" },
  description: [
    "40 Meadowbrook is a three-bedroom unit in a small multiplex on a quiet street in North York. The unit has been newly renovated with new laminate floors, updated appliances, and new fixtures.",
    "Two full bathrooms, a separate living room, and a private balcony. Water is included in the rent. Coin-operated laundry is available in the building, and there is a dedicated parking spot in the back.",
    "A short walk away is the Lawrence West TTC station. With nearby schools, parks, and shopping at Lawrence Allen Centre.",
  ],
  details: [
    { label: "Rent",      value: "$2,800 / month" },
    { label: "Bedrooms",  value: "3" },
    { label: "Bathrooms", value: "2" },
    { label: "Size",      value: "800 sq. ft." },
    { label: "Type",      value: "Apartment / Multiplex" },
    { label: "Laundry",   value: "Coin-operated In Building" },
    { label: "Parking",   value: "Included" },
  ],
features: [
    { title: "3 Bedrooms",           body: "Spacious master bedroom plus two additional bedrooms, each with good natural light and closet space." },
    { title: "2 Full Bathrooms",     body: "Soaking tub with hand shower in one, separate shower stall in the other." },
    { title: "Updated Kitchen",      body: "Full-height white cabinetry, granite-look countertops, double stainless sink, and included appliances." },
    { title: "Private Balcony",      body: "A door off the living room opens to your own outdoor space." },
    { title: "New Laminate Floors",  body: "Wide-plank grey laminate throughout — clean, modern, and easy to maintain." },
    { title: "Parking Included",     body: "One dedicated parking space included with the unit." },
    { title: "Baseboard Heating",    body: "Per-room electric baseboard heaters for comfortable, controllable warmth." },
    { title: "TTC Accessible",       body: "Multiple bus routes within walking distance with easy connections to the subway." },
    { title: "Quiet Street",         body: "Mature, tree-lined residential street in a well-established neighbourhood." },
  ],
  photos: [
    { src: "photos/exterior-1.jpg",        caption: "Exterior" },
    { src: "photos/living-room-1.jpg",     caption: "Living Room" },
    { src: "photos/living-room-2.jpg",     caption: "Living Room" },
    { src: "photos/kitchen-1.jpg",         caption: "Kitchen" },
    { src: "photos/kitchen-3.jpg",         caption: "Kitchen" },
    { src: "photos/master-bedroom-1.jpg",  caption: "Master Bedroom" },
    { src: "photos/master-bedroom-2.jpg",  caption: "Master Bedroom" },
    { src: "photos/master-bathroom-1.jpg", caption: "Master Bathroom" },
    { src: "photos/master-bathroom-2.jpg", caption: "Master Bathroom" },
    { src: "photos/second-bedroom-1.jpg",  caption: "Second Bedroom" },
    { src: "photos/second-bedroom-2.jpg",  caption: "Second Bedroom" },
    { src: "photos/third-bedroom-1.jpg",   caption: "Third Bedroom" },
    { src: "photos/third-bedroom-2.jpg",   caption: "Third Bedroom" },
    { src: "photos/bathroom-1.jpg",        caption: "Bathroom" },
    { src: "photos/bathroom-2.jpg",        caption: "Bathroom" },
    { src: "photos/bathroom-3.jpg",        caption: "Bathroom" },
    { src: "photos/hallway-1.jpg",         caption: "Hallway" },
    { src: "photos/hallway-2.jpg",         caption: "Hallway" },
    { src: "photos/hallway-3.jpg",         caption: "Hallway" },
    { src: "photos/entranceway-1.jpg",     caption: "Entranceway" },
    { src: "photos/parking-space-1.jpg",   caption: "Parking Space" },
  ],
  nearby: ["TTC subway station", "Schools", "Parks & Green Space", "Grocery & Shopping", "Cafes & Restaurants"],
}// patch - this gets merged manually
