export const listing = {
  address:   "40 Meadowbrook Rd",
  city:      "Toronto",
  province:  "ON",
  price:     2800,
  beds:      3,
  baths:     2,
  sqft:      1000,
  available: "Available Now",
  type:      "Apartment — Multiplex",
  contact: { email: "your@email.com", phone: "+1 (416) 000-0000" },
  description: [
    "Welcome to 40 Meadowbrook Road — a generously sized three-bedroom apartment with updated interiors in a quiet residential multiplex. Fresh laminate flooring runs throughout, and oversized windows flood every room with natural light.",
    "The kitchen has full-height white cabinetry, granite-look countertops, and a double stainless steel sink. Two full bathrooms serve the unit — one with a soaking tub and hand shower, the other with a separate shower stall. A balcony door off the living room gives you your own outdoor space.",
    "Electric baseboard heating throughout. Mature, tree-lined street with easy access to TTC bus routes, schools, parks, and everyday shopping.",
  ],
  details: [
    { label: "Rent",      value: "$2,800 / month" },
    { label: "Bedrooms",  value: "3" },
    { label: "Bathrooms", value: "2" },
    { label: "Size",      value: "~1,000 sq. ft." },
    { label: "Type",      value: "Apartment / Multiplex" },
    { label: "Heating",   value: "Electric baseboard" },
    { label: "Laundry",   value: "Inquire" },
    { label: "Parking",   value: "Included" },
    { label: "Pets",      value: "Inquire" },
    { label: "Available", value: "Now" },
  ],
  features: [
    "3 spacious bedrooms",
    "2 full bathrooms",
    "Master bedroom with ensuite",
    "Updated kitchen with appliances",
    "Private balcony access",
    "New laminate flooring",
    "Large windows throughout",
    "Electric baseboard heating",
    "Parking space included",
    "TTC bus routes nearby",
    "Schools & parks within walking distance",
    "Quiet residential street",
  ],
  photos: [
    { src: "/photos/living-room-1.jpg",      caption: "Living Room" },
    { src: "/photos/living-room-2.jpg",      caption: "Living Room" },
    { src: "/photos/kitchen-1.jpg",          caption: "Kitchen" },
    { src: "/photos/kitchen-3.jpg",          caption: "Kitchen" },
    { src: "/photos/master-bedroom-1.jpg",   caption: "Master Bedroom" },
    { src: "/photos/master-bedroom-2.jpg",   caption: "Master Bedroom" },
    { src: "/photos/master-bathroom-1.jpg",  caption: "Master Bathroom" },
    { src: "/photos/master-bathroom-2.jpg",  caption: "Master Bathroom" },
    { src: "/photos/second-bedroom-1.jpg",   caption: "Second Bedroom" },
    { src: "/photos/second-bedroom-2.jpg",   caption: "Second Bedroom" },
    { src: "/photos/third-bedroom-1.jpg",    caption: "Third Bedroom" },
    { src: "/photos/third-bedroom-2.jpg",    caption: "Third Bedroom" },
    { src: "/photos/bathroom-1.jpg",         caption: "Bathroom" },
    { src: "/photos/bathroom-2.jpg",         caption: "Bathroom" },
    { src: "/photos/bathroom-3.jpg",         caption: "Bathroom" },
    { src: "/photos/hallway-1.jpg",          caption: "Hallway" },
    { src: "/photos/hallway-2.jpg",          caption: "Hallway" },
    { src: "/photos/hallway-3.jpg",          caption: "Hallway" },
    { src: "/photos/entranceway-1.jpg",      caption: "Entranceway" },
    { src: "/photos/exterior-1.jpg",         caption: "Exterior" },
    { src: "/photos/parking-space-1.jpg",    caption: "Parking Space" },
  ],
}
